services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    name: app_network
    external: true
