services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # MinIO (for object storage)
  minio:
    image: minio/minio
    env_file:
      - .env
    ports:
      - '9000:9000'
    command: server /data
    networks:
      - app-network

  # Backend Service
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - minio
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    networks:
      - app-network

volumes:
  postgres-data:


networks:
  app-network:
    driver: bridge
    name: app_network
